version: '3'
services:

    #PHP Service
    bicycle_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: bicycle_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: walet_app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    bicycle_db:
        image: mysql
        container_name: bicycle_db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: bicycle_db
            MYSQL_ROOT_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    data:
        driver: local
